### ISSUE TITLE
Error doesn't make sense to the user when uploading heimdall_tools jsons

### ISSUE THREAD

**Issue by ejaronne** [mitre/inspecjs#13]
https://github.com/mitre/inspecjs/blob/master/src/fileparse.ts 
"Unable to convert inspec json output. Please verify it's from an up-to-date version of the program!"

Error doesn't make sense to the user when uploading heimdall_tools jsons

**Comment by Amndeep7** [comment]
https://github.com/mitre/heimdall2/blob/master/libs/inspecjs/src/fileparse.ts#L70-L74

Seems to be a better error message.  If this is still not good enough, please make a new issue in the heimdall2 repo against inspecjs @ejaronne.
